CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'.....E...E..........EE.............E...F...F........FE.....F.F...........F.EE......F..........E...E.\n======================================================================\nERROR: test13 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 90, in test13\n    self.assertEqual(patched_source(*input_13), original_source(*input_13))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_acc_qb.py", line 10, in patched_func\n    s += x[i]\nIndexError: list index out of range\n\n======================================================================\nERROR: test17 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 114, in test17\n    self.assertEqual(patched_source(*input_17), original_source(*input_17))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_acc_qb.py", line 10, in patched_func\n    s += x[i]\nIndexError: list index out of range\n\n======================================================================\nERROR: test27 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 174, in test27\n    self.assertEqual(patched_source(*input_27), original_source(*input_27))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_acc_qb.py", line 10, in patched_func\n    s += x[i]\nIndexError: list index out of range\n\n======================================================================\nERROR: test28 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 180, in test28\n    self.assertEqual(patched_source(*input_28), original_source(*input_28))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_acc_qb.py", line 10, in patched_func\n    s += x[i]\nIndexError: list index out of range\n\n======================================================================\nERROR: test40 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 252, in test40\n    self.assertEqual(patched_source(*input_40), original_source(*input_40))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_acc_qb.py", line 10, in patched_func\n    s += x[i]\nIndexError: list index out of range\n\n======================================================================\nERROR: test57 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 354, in test57\n    self.assertEqual(patched_source(*input_57), original_source(*input_57))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_acc_qb.py", line 10, in patched_func\n    s += x[i]\nIndexError: list index out of range\n\n======================================================================\nERROR: test77 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 474, in test77\n    self.assertEqual(patched_source(*input_77), original_source(*input_77))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_acc_qb.py", line 10, in patched_func\n    s += x[i]\nIndexError: list index out of range\n\n======================================================================\nERROR: test78 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 480, in test78\n    self.assertEqual(patched_source(*input_78), original_source(*input_78))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_acc_qb.py", line 10, in patched_func\n    s += x[i]\nIndexError: list index out of range\n\n======================================================================\nERROR: test94 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 576, in test94\n    self.assertEqual(patched_source(*input_94), original_source(*input_94))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_acc_qb.py", line 10, in patched_func\n    s += x[i]\nIndexError: list index out of range\n\n======================================================================\nERROR: test98 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 600, in test98\n    self.assertEqual(patched_source(*input_98), original_source(*input_98))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_acc_qb.py", line 10, in patched_func\n    s += x[i]\nIndexError: list index out of range\n\n======================================================================\nFAIL: test44 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 276, in test44\n    self.assertEqual(patched_source(*input_44), original_source(*input_44))\nAssertionError: Lists differ: [\'-1\'] != [12]\n\nFirst differing element 0:\n\'-1\'\n12\n\n- [\'-1\']\n+ [12]\n\n======================================================================\nFAIL: test48 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 300, in test48\n    self.assertEqual(patched_source(*input_48), original_source(*input_48))\nAssertionError: Lists differ: [\'-1\'] != [12]\n\nFirst differing element 0:\n\'-1\'\n12\n\n- [\'-1\']\n+ [12]\n\n======================================================================\nFAIL: test56 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 348, in test56\n    self.assertEqual(patched_source(*input_56), original_source(*input_56))\nAssertionError: Lists differ: [\'-1\'] != [12]\n\nFirst differing element 0:\n\'-1\'\n12\n\n- [\'-1\']\n+ [12]\n\n======================================================================\nFAIL: test62 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 384, in test62\n    self.assertEqual(patched_source(*input_62), original_source(*input_62))\nAssertionError: Lists differ: [\'-1\'] != [12]\n\nFirst differing element 0:\n\'-1\'\n12\n\n- [\'-1\']\n+ [12]\n\n======================================================================\nFAIL: test64 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 396, in test64\n    self.assertEqual(patched_source(*input_64), original_source(*input_64))\nAssertionError: Lists differ: [\'-1\'] != [12]\n\nFirst differing element 0:\n\'-1\'\n12\n\n- [\'-1\']\n+ [12]\n\n======================================================================\nFAIL: test75 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 462, in test75\n    self.assertEqual(patched_source(*input_75), original_source(*input_75))\nAssertionError: Lists differ: [\'-1\'] != [12]\n\nFirst differing element 0:\n\'-1\'\n12\n\n- [\'-1\']\n+ [12]\n\n======================================================================\nFAIL: test84 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 516, in test84\n    self.assertEqual(patched_source(*input_84), original_source(*input_84))\nAssertionError: Lists differ: [\'-1\'] != [12]\n\nFirst differing element 0:\n\'-1\'\n12\n\n- [\'-1\']\n+ [12]\n\n----------------------------------------------------------------------\nRan 100 tests in 0.008s\n\nFAILED (failures=7, errors=10)\n')