CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'FFF.F.FF.F\n======================================================================\nFAIL: test0 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 12, in test0\n    self.assertEqual(patched_source(input_0), original_source(input_0))\nAssertionError: Lists differ: [28] != [24]\n\nFirst differing element 0:\n28\n24\n\n- [28]\n?   ^\n\n+ [24]\n?   ^\n\n\n======================================================================\nFAIL: test1 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 18, in test1\n    self.assertEqual(patched_source(input_1), original_source(input_1))\nAssertionError: Lists differ: [28] != [24]\n\nFirst differing element 0:\n28\n24\n\n- [28]\n?   ^\n\n+ [24]\n?   ^\n\n\n======================================================================\nFAIL: test2 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 24, in test2\n    self.assertEqual(patched_source(input_2), original_source(input_2))\nAssertionError: Lists differ: [32] != [44]\n\nFirst differing element 0:\n32\n44\n\n- [32]\n+ [44]\n\n======================================================================\nFAIL: test4 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 36, in test4\n    self.assertEqual(patched_source(input_4), original_source(input_4))\nAssertionError: Lists differ: [16] != [20]\n\nFirst differing element 0:\n16\n20\n\n- [16]\n+ [20]\n\n======================================================================\nFAIL: test6 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 48, in test6\n    self.assertEqual(patched_source(input_6), original_source(input_6))\nAssertionError: Lists differ: [52] != [40]\n\nFirst differing element 0:\n52\n40\n\n- [52]\n+ [40]\n\n======================================================================\nFAIL: test7 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 54, in test7\n    self.assertEqual(patched_source(input_7), original_source(input_7))\nAssertionError: Lists differ: [40] != [32]\n\nFirst differing element 0:\n40\n32\n\n- [40]\n+ [32]\n\n======================================================================\nFAIL: test9 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 66, in test9\n    self.assertEqual(patched_source(input_9), original_source(input_9))\nAssertionError: Lists differ: [28] != [24]\n\nFirst differing element 0:\n28\n24\n\n- [28]\n?   ^\n\n+ [24]\n?   ^\n\n\n----------------------------------------------------------------------\nRan 10 tests in 0.002s\n\nFAILED (failures=7)\n')