CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'...F.F...F\n======================================================================\nFAIL: test3 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 30, in test3\n    self.assertEqual(patched_source(input_3), original_source(input_3))\nAssertionError: Lists differ: [11] != [25]\n\nFirst differing element 0:\n11\n25\n\n- [11]\n+ [25]\n\n======================================================================\nFAIL: test5 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 42, in test5\n    self.assertEqual(patched_source(input_5), original_source(input_5))\nAssertionError: Lists differ: [26] != [42]\n\nFirst differing element 0:\n26\n42\n\n- [26]\n?   -\n\n+ [42]\n?  +\n\n\n======================================================================\nFAIL: test9 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 66, in test9\n    self.assertEqual(patched_source(input_9), original_source(input_9))\nAssertionError: Lists differ: [27] != [41]\n\nFirst differing element 0:\n27\n41\n\n- [27]\n+ [41]\n\n----------------------------------------------------------------------\nRan 10 tests in 0.001s\n\nFAILED (failures=3)\n')