CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'......F...........................F..........E..E....................\n======================================================================\nERROR: test5 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 42, in test5\n    self.assertEqual(patched_source(input_5), original_source(input_5))\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_acc_qb.py", line 4, in patched_func\n    (a, b, c) = map(int, args[0].split())\nValueError: too many values to unpack (expected 3)\n\n======================================================================\nERROR: test52 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 324, in test52\n    self.assertEqual(patched_source(input_52), original_source(input_52))\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_acc_qb.py", line 4, in patched_func\n    (a, b, c) = map(int, args[0].split())\nValueError: too many values to unpack (expected 3)\n\n======================================================================\nFAIL: test14 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 96, in test14\n    self.assertEqual(patched_source(input_14), original_source(input_14))\nAssertionError: Lists differ: [14] != [15]\n\nFirst differing element 0:\n14\n15\n\n- [14]\n?   ^\n\n+ [15]\n?   ^\n\n\n======================================================================\nFAIL: test4 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 36, in test4\n    self.assertEqual(patched_source(input_4), original_source(input_4))\nAssertionError: Lists differ: [14] != [15]\n\nFirst differing element 0:\n14\n15\n\n- [14]\n?   ^\n\n+ [15]\n?   ^\n\n\n----------------------------------------------------------------------\nRan 69 tests in 0.004s\n\nFAILED (failures=2, errors=2)\n')