CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'.........F.....F....E.\n======================================================================\nERROR: test8 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 60, in test8\n    self.assertEqual(patched_source(*input_8), original_source(*input_8))\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_acc_qb.py", line 22, in patched_func\n    s = swap(s)\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_acc_qb.py", line 16, in swap\n    if ((s[i] == \'B\') and (s[(i + 1)] == \'G\')):\nIndexError: list index out of range\n\n======================================================================\nFAIL: test17 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 114, in test17\n    self.assertEqual(patched_source(*input_17), original_source(*input_17))\nAssertionError: Lists differ: [\'GBGB\'] != [\'GGBB\']\n\nFirst differing element 0:\n\'GBGB\'\n\'GGBB\'\n\n- [\'GBGB\']\n?     -\n\n+ [\'GGBB\']\n?    +\n\n\n======================================================================\nFAIL: test3 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 30, in test3\n    self.assertEqual(patched_source(*input_3), original_source(*input_3))\nAssertionError: Lists differ: [\'GBBGB\'] != [\'GBGBB\']\n\nFirst differing element 0:\n\'GBBGB\'\n\'GBGBB\'\n\n- [\'GBBGB\']\n?      -\n\n+ [\'GBGBB\']\n?     +\n\n\n----------------------------------------------------------------------\nRan 22 tests in 0.003s\n\nFAILED (failures=2, errors=1)\n')