CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'.....FF.F..F..F.....FF..FF.....FF.F.FFF..F..\n======================================================================\nFAIL: test13 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 90, in test13\n    self.assertEqual(patched_source(input_13), original_source(input_13))\nAssertionError: Lists differ: [1] != [2]\n\nFirst differing element 0:\n1\n2\n\n- [1]\n+ [2]\n\n======================================================================\nFAIL: test14 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 96, in test14\n    self.assertEqual(patched_source(input_14), original_source(input_14))\nAssertionError: Lists differ: [1] != [2]\n\nFirst differing element 0:\n1\n2\n\n- [1]\n+ [2]\n\n======================================================================\nFAIL: test16 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 108, in test16\n    self.assertEqual(patched_source(input_16), original_source(input_16))\nAssertionError: Lists differ: [1] != [2]\n\nFirst differing element 0:\n1\n2\n\n- [1]\n+ [2]\n\n======================================================================\nFAIL: test19 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 126, in test19\n    self.assertEqual(patched_source(input_19), original_source(input_19))\nAssertionError: Lists differ: [2] != [4]\n\nFirst differing element 0:\n2\n4\n\n- [2]\n+ [4]\n\n======================================================================\nFAIL: test21 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 138, in test21\n    self.assertEqual(patched_source(input_21), original_source(input_21))\nAssertionError: Lists differ: [1] != [2]\n\nFirst differing element 0:\n1\n2\n\n- [1]\n+ [2]\n\n======================================================================\nFAIL: test27 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 174, in test27\n    self.assertEqual(patched_source(input_27), original_source(input_27))\nAssertionError: Lists differ: [1] != [2]\n\nFirst differing element 0:\n1\n2\n\n- [1]\n+ [2]\n\n======================================================================\nFAIL: test28 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 180, in test28\n    self.assertEqual(patched_source(input_28), original_source(input_28))\nAssertionError: Lists differ: [1] != [2]\n\nFirst differing element 0:\n1\n2\n\n- [1]\n+ [2]\n\n======================================================================\nFAIL: test30 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 192, in test30\n    self.assertEqual(patched_source(input_30), original_source(input_30))\nAssertionError: Lists differ: [1] != [2]\n\nFirst differing element 0:\n1\n2\n\n- [1]\n+ [2]\n\n======================================================================\nFAIL: test31 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 198, in test31\n    self.assertEqual(patched_source(input_31), original_source(input_31))\nAssertionError: Lists differ: [1] != [2]\n\nFirst differing element 0:\n1\n2\n\n- [1]\n+ [2]\n\n======================================================================\nFAIL: test37 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 234, in test37\n    self.assertEqual(patched_source(input_37), original_source(input_37))\nAssertionError: Lists differ: [1] != [2]\n\nFirst differing element 0:\n1\n2\n\n- [1]\n+ [2]\n\n======================================================================\nFAIL: test38 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 240, in test38\n    self.assertEqual(patched_source(input_38), original_source(input_38))\nAssertionError: Lists differ: [1] != [2]\n\nFirst differing element 0:\n1\n2\n\n- [1]\n+ [2]\n\n======================================================================\nFAIL: test4 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 36, in test4\n    self.assertEqual(patched_source(input_4), original_source(input_4))\nAssertionError: Lists differ: [1] != [2]\n\nFirst differing element 0:\n1\n2\n\n- [1]\n+ [2]\n\n======================================================================\nFAIL: test41 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 258, in test41\n    self.assertEqual(patched_source(input_41), original_source(input_41))\nAssertionError: Lists differ: [1] != [2]\n\nFirst differing element 0:\n1\n2\n\n- [1]\n+ [2]\n\n======================================================================\nFAIL: test42 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 264, in test42\n    self.assertEqual(patched_source(input_42), original_source(input_42))\nAssertionError: Lists differ: [2] != [4]\n\nFirst differing element 0:\n2\n4\n\n- [2]\n+ [4]\n\n======================================================================\nFAIL: test43 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 270, in test43\n    self.assertEqual(patched_source(input_43), original_source(input_43))\nAssertionError: Lists differ: [1] != [2]\n\nFirst differing element 0:\n1\n2\n\n- [1]\n+ [2]\n\n======================================================================\nFAIL: test7 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 54, in test7\n    self.assertEqual(patched_source(input_7), original_source(input_7))\nAssertionError: Lists differ: [1] != [2]\n\nFirst differing element 0:\n1\n2\n\n- [1]\n+ [2]\n\n----------------------------------------------------------------------\nRan 44 tests in 0.005s\n\nFAILED (failures=16)\n')