CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'...F.EFE..\n======================================================================\nERROR: test5 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 42, in test5\n    self.assertEqual(patched_source(input_5), original_source(input_5))\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_acc_qb.py", line 4, in patched_func\n    n = int(args[0])\nValueError: invalid literal for int() with base 10: \'5 44 09 188\'\n\n======================================================================\nERROR: test7 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 54, in test7\n    self.assertEqual(patched_source(input_7), original_source(input_7))\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_acc_qb.py", line 4, in patched_func\n    n = int(args[0])\nValueError: invalid literal for int() with base 10: \'0 101010 1111\'\n\n======================================================================\nFAIL: test3 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 30, in test3\n    self.assertEqual(patched_source(*input_3), original_source(*input_3))\nAssertionError: Lists differ: [\'11010040\'] != [\'1101004\']\n\nFirst differing element 0:\n\'11010040\'\n\'1101004\'\n\n- [\'11010040\']\n?          -\n\n+ [\'1101004\']\n\n======================================================================\nFAIL: test6 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 48, in test6\n    self.assertEqual(patched_source(*input_6), original_source(*input_6))\nAssertionError: Lists differ: [\'1110\'] != [\'111\']\n\nFirst differing element 0:\n\'1110\'\n\'111\'\n\n- [\'1110\']\n?      -\n\n+ [\'111\']\n\n----------------------------------------------------------------------\nRan 10 tests in 0.002s\n\nFAILED (failures=2, errors=2)\n')