CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'F......F.....F............FFFFFF...FF....\n======================================================================\nFAIL: test0 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 12, in test0\n    self.assertEqual(patched_source(input_0), original_source(input_0))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test15 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 102, in test15\n    self.assertEqual(patched_source(input_15), original_source(input_15))\nAssertionError: Lists differ: [0] != [1]\n\nFirst differing element 0:\n0\n1\n\n- [0]\n+ [1]\n\n======================================================================\nFAIL: test20 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 132, in test20\n    self.assertEqual(patched_source(input_20), original_source(input_20))\nAssertionError: Lists differ: [0] != [1]\n\nFirst differing element 0:\n0\n1\n\n- [0]\n+ [1]\n\n======================================================================\nFAIL: test32 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 204, in test32\n    self.assertEqual(patched_source(input_32), original_source(input_32))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test33 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 210, in test33\n    self.assertEqual(patched_source(input_33), original_source(input_33))\nAssertionError: Lists differ: [0] != [1]\n\nFirst differing element 0:\n0\n1\n\n- [0]\n+ [1]\n\n======================================================================\nFAIL: test34 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 216, in test34\n    self.assertEqual(patched_source(input_34), original_source(input_34))\nAssertionError: Lists differ: [0] != [1]\n\nFirst differing element 0:\n0\n1\n\n- [0]\n+ [1]\n\n======================================================================\nFAIL: test35 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 222, in test35\n    self.assertEqual(patched_source(input_35), original_source(input_35))\nAssertionError: Lists differ: [0] != [1]\n\nFirst differing element 0:\n0\n1\n\n- [0]\n+ [1]\n\n======================================================================\nFAIL: test36 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 228, in test36\n    self.assertEqual(patched_source(input_36), original_source(input_36))\nAssertionError: Lists differ: [0] != [1]\n\nFirst differing element 0:\n0\n1\n\n- [0]\n+ [1]\n\n======================================================================\nFAIL: test37 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 234, in test37\n    self.assertEqual(patched_source(input_37), original_source(input_37))\nAssertionError: Lists differ: [0] != [1]\n\nFirst differing element 0:\n0\n1\n\n- [0]\n+ [1]\n\n======================================================================\nFAIL: test40 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 252, in test40\n    self.assertEqual(patched_source(input_40), original_source(input_40))\nAssertionError: Lists differ: [0] != [1]\n\nFirst differing element 0:\n0\n1\n\n- [0]\n+ [1]\n\n======================================================================\nFAIL: test5 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 42, in test5\n    self.assertEqual(patched_source(input_5), original_source(input_5))\nAssertionError: Lists differ: [0] != [1]\n\nFirst differing element 0:\n0\n1\n\n- [0]\n+ [1]\n\n----------------------------------------------------------------------\nRan 41 tests in 0.007s\n\nFAILED (failures=11)\n')