CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'..............E.......F..F.......................................................................F..\n======================================================================\nERROR: test21 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 138, in test21\n    self.assertEqual(patched_source(input_21), original_source(input_21))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_acc_qb.py", line 5, in patched_func\n    l1 = list(map(int, args[1].split()))\nIndexError: tuple index out of range\n\n======================================================================\nFAIL: test29 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 186, in test29\n    self.assertEqual(patched_source(*input_29), original_source(*input_29))\nAssertionError: Lists differ: [\'Yes\'] != [\'No\']\n\nFirst differing element 0:\n\'Yes\'\n\'No\'\n\n- [\'Yes\']\n+ [\'No\']\n\n======================================================================\nFAIL: test31 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 198, in test31\n    self.assertEqual(patched_source(*input_31), original_source(*input_31))\nAssertionError: Lists differ: [\'Yes\'] != [\'No\']\n\nFirst differing element 0:\n\'Yes\'\n\'No\'\n\n- [\'Yes\']\n+ [\'No\']\n\n======================================================================\nFAIL: test97 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 594, in test97\n    self.assertEqual(patched_source(*input_97), original_source(*input_97))\nAssertionError: Lists differ: [\'Yes\'] != [\'No\']\n\nFirst differing element 0:\n\'Yes\'\n\'No\'\n\n- [\'Yes\']\n+ [\'No\']\n\n----------------------------------------------------------------------\nRan 100 tests in 0.006s\n\nFAILED (failures=3, errors=1)\n')