CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'....F.F.F.F......F....F......F....FF.................F....F....FF....F..F.....F..FFFFF..F.......F\n======================================================================\nFAIL: test12 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 84, in test12\n    self.assertEqual(patched_source(input_12), original_source(input_12))\nAssertionError: Lists differ: [0] != [2]\n\nFirst differing element 0:\n0\n2\n\n- [0]\n+ [2]\n\n======================================================================\nFAIL: test14 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 96, in test14\n    self.assertEqual(patched_source(input_14), original_source(input_14))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test16 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 108, in test16\n    self.assertEqual(patched_source(input_16), original_source(input_16))\nAssertionError: Lists differ: [1] != [2]\n\nFirst differing element 0:\n1\n2\n\n- [1]\n+ [2]\n\n======================================================================\nFAIL: test18 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 120, in test18\n    self.assertEqual(patched_source(input_18), original_source(input_18))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test24 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 156, in test24\n    self.assertEqual(patched_source(input_24), original_source(input_24))\nAssertionError: Lists differ: [0] != [2]\n\nFirst differing element 0:\n0\n2\n\n- [0]\n+ [2]\n\n======================================================================\nFAIL: test29 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 186, in test29\n    self.assertEqual(patched_source(input_29), original_source(input_29))\nAssertionError: Lists differ: [1] != [2]\n\nFirst differing element 0:\n1\n2\n\n- [1]\n+ [2]\n\n======================================================================\nFAIL: test35 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 222, in test35\n    self.assertEqual(patched_source(input_35), original_source(input_35))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test4 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 36, in test4\n    self.assertEqual(patched_source(input_4), original_source(input_4))\nAssertionError: Lists differ: [1] != [2]\n\nFirst differing element 0:\n1\n2\n\n- [1]\n+ [2]\n\n======================================================================\nFAIL: test40 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 252, in test40\n    self.assertEqual(patched_source(input_40), original_source(input_40))\nAssertionError: Lists differ: [0] != [2]\n\nFirst differing element 0:\n0\n2\n\n- [0]\n+ [2]\n\n======================================================================\nFAIL: test57 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 354, in test57\n    self.assertEqual(patched_source(input_57), original_source(input_57))\nAssertionError: Lists differ: [0] != [1]\n\nFirst differing element 0:\n0\n1\n\n- [0]\n+ [1]\n\n======================================================================\nFAIL: test61 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 378, in test61\n    self.assertEqual(patched_source(input_61), original_source(input_61))\nAssertionError: Lists differ: [0] != [2]\n\nFirst differing element 0:\n0\n2\n\n- [0]\n+ [2]\n\n======================================================================\nFAIL: test66 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 408, in test66\n    self.assertEqual(patched_source(input_66), original_source(input_66))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test67 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 414, in test67\n    self.assertEqual(patched_source(input_67), original_source(input_67))\nAssertionError: Lists differ: [0] != [2]\n\nFirst differing element 0:\n0\n2\n\n- [0]\n+ [2]\n\n======================================================================\nFAIL: test71 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 438, in test71\n    self.assertEqual(patched_source(input_71), original_source(input_71))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test74 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 456, in test74\n    self.assertEqual(patched_source(input_74), original_source(input_74))\nAssertionError: Lists differ: [1] != [2]\n\nFirst differing element 0:\n1\n2\n\n- [1]\n+ [2]\n\n======================================================================\nFAIL: test8 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 60, in test8\n    self.assertEqual(patched_source(input_8), original_source(input_8))\nAssertionError: Lists differ: [0] != [2]\n\nFirst differing element 0:\n0\n2\n\n- [0]\n+ [2]\n\n======================================================================\nFAIL: test82 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 504, in test82\n    self.assertEqual(patched_source(input_82), original_source(input_82))\nAssertionError: Lists differ: [0] != [2]\n\nFirst differing element 0:\n0\n2\n\n- [0]\n+ [2]\n\n======================================================================\nFAIL: test83 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 510, in test83\n    self.assertEqual(patched_source(input_83), original_source(input_83))\nAssertionError: Lists differ: [1] != [2]\n\nFirst differing element 0:\n1\n2\n\n- [1]\n+ [2]\n\n======================================================================\nFAIL: test84 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 516, in test84\n    self.assertEqual(patched_source(input_84), original_source(input_84))\nAssertionError: Lists differ: [0] != [2]\n\nFirst differing element 0:\n0\n2\n\n- [0]\n+ [2]\n\n======================================================================\nFAIL: test85 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 522, in test85\n    self.assertEqual(patched_source(input_85), original_source(input_85))\nAssertionError: Lists differ: [0] != [2]\n\nFirst differing element 0:\n0\n2\n\n- [0]\n+ [2]\n\n======================================================================\nFAIL: test86 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 528, in test86\n    self.assertEqual(patched_source(input_86), original_source(input_86))\nAssertionError: Lists differ: [1] != [2]\n\nFirst differing element 0:\n1\n2\n\n- [1]\n+ [2]\n\n======================================================================\nFAIL: test89 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 546, in test89\n    self.assertEqual(patched_source(input_89), original_source(input_89))\nAssertionError: Lists differ: [1] != [2]\n\nFirst differing element 0:\n1\n2\n\n- [1]\n+ [2]\n\n======================================================================\nFAIL: test96 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 588, in test96\n    self.assertEqual(patched_source(input_96), original_source(input_96))\nAssertionError: Lists differ: [1] != [2]\n\nFirst differing element 0:\n1\n2\n\n- [1]\n+ [2]\n\n----------------------------------------------------------------------\nRan 97 tests in 0.009s\n\nFAILED (failures=23)\n')