CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'............................................................................F......\n======================================================================\nFAIL: test78 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 480, in test78\n    self.assertEqual(patched_source(input_78), original_source(input_78))\nAssertionError: Lists differ: [\'No\'] != [\'Yes\']\n\nFirst differing element 0:\n\'No\'\n\'Yes\'\n\n- [\'No\']\n+ [\'Yes\']\n\n----------------------------------------------------------------------\nRan 83 tests in 0.004s\n\nFAILED (failures=1)\n')