CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'.........F.FF......F.......F..F......F.....F.F..F.............FF...................FFF..............\n======================================================================\nFAIL: test17 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 114, in test17\n    self.assertEqual(patched_source(input_17), original_source(input_17))\nAssertionError: Lists differ: [3] != [2]\n\nFirst differing element 0:\n3\n2\n\n- [3]\n+ [2]\n\n======================================================================\nFAIL: test19 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 126, in test19\n    self.assertEqual(patched_source(input_19), original_source(input_19))\nAssertionError: Lists differ: [3] != [2]\n\nFirst differing element 0:\n3\n2\n\n- [3]\n+ [2]\n\n======================================================================\nFAIL: test2 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 24, in test2\n    self.assertEqual(patched_source(input_2), original_source(input_2))\nAssertionError: Lists differ: [3] != [2]\n\nFirst differing element 0:\n3\n2\n\n- [3]\n+ [2]\n\n======================================================================\nFAIL: test26 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 168, in test26\n    self.assertEqual(patched_source(input_26), original_source(input_26))\nAssertionError: Lists differ: [2] != [1]\n\nFirst differing element 0:\n2\n1\n\n- [2]\n+ [1]\n\n======================================================================\nFAIL: test33 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 210, in test33\n    self.assertEqual(patched_source(input_33), original_source(input_33))\nAssertionError: Lists differ: [2] != [1]\n\nFirst differing element 0:\n2\n1\n\n- [2]\n+ [1]\n\n======================================================================\nFAIL: test36 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 228, in test36\n    self.assertEqual(patched_source(input_36), original_source(input_36))\nAssertionError: Lists differ: [4] != [3]\n\nFirst differing element 0:\n4\n3\n\n- [4]\n+ [3]\n\n======================================================================\nFAIL: test42 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 264, in test42\n    self.assertEqual(patched_source(input_42), original_source(input_42))\nAssertionError: Lists differ: [4] != [3]\n\nFirst differing element 0:\n4\n3\n\n- [4]\n+ [3]\n\n======================================================================\nFAIL: test48 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 300, in test48\n    self.assertEqual(patched_source(input_48), original_source(input_48))\nAssertionError: Lists differ: [4] != [3]\n\nFirst differing element 0:\n4\n3\n\n- [4]\n+ [3]\n\n======================================================================\nFAIL: test5 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 42, in test5\n    self.assertEqual(patched_source(input_5), original_source(input_5))\nAssertionError: Lists differ: [2] != [1]\n\nFirst differing element 0:\n2\n1\n\n- [2]\n+ [1]\n\n======================================================================\nFAIL: test52 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 324, in test52\n    self.assertEqual(patched_source(input_52), original_source(input_52))\nAssertionError: Lists differ: [3] != [2]\n\nFirst differing element 0:\n3\n2\n\n- [3]\n+ [2]\n\n======================================================================\nFAIL: test65 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 402, in test65\n    self.assertEqual(patched_source(input_65), original_source(input_65))\nAssertionError: Lists differ: [3] != [2]\n\nFirst differing element 0:\n3\n2\n\n- [3]\n+ [2]\n\n======================================================================\nFAIL: test66 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 408, in test66\n    self.assertEqual(patched_source(input_66), original_source(input_66))\nAssertionError: Lists differ: [5] != [4]\n\nFirst differing element 0:\n5\n4\n\n- [5]\n+ [4]\n\n======================================================================\nFAIL: test84 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 516, in test84\n    self.assertEqual(patched_source(input_84), original_source(input_84))\nAssertionError: Lists differ: [4] != [3]\n\nFirst differing element 0:\n4\n3\n\n- [4]\n+ [3]\n\n======================================================================\nFAIL: test85 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 522, in test85\n    self.assertEqual(patched_source(input_85), original_source(input_85))\nAssertionError: Lists differ: [4] != [3]\n\nFirst differing element 0:\n4\n3\n\n- [4]\n+ [3]\n\n======================================================================\nFAIL: test86 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 528, in test86\n    self.assertEqual(patched_source(input_86), original_source(input_86))\nAssertionError: Lists differ: [3] != [2]\n\nFirst differing element 0:\n3\n2\n\n- [3]\n+ [2]\n\n----------------------------------------------------------------------\nRan 100 tests in 0.008s\n\nFAILED (failures=15)\n')