CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'F.F.....F.............F..........F..F.............F................F...................F............\n======================================================================\nFAIL: test0 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 12, in test0\n    self.assertEqual(patched_source(input_0), original_source(input_0))\nAssertionError: Lists differ: [4] != [3]\n\nFirst differing element 0:\n4\n3\n\n- [4]\n+ [3]\n\n======================================================================\nFAIL: test10 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 72, in test10\n    self.assertEqual(patched_source(input_10), original_source(input_10))\nAssertionError: Lists differ: [2] != [1]\n\nFirst differing element 0:\n2\n1\n\n- [2]\n+ [1]\n\n======================================================================\nFAIL: test16 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 108, in test16\n    self.assertEqual(patched_source(input_16), original_source(input_16))\nAssertionError: Lists differ: [3] != [2]\n\nFirst differing element 0:\n3\n2\n\n- [3]\n+ [2]\n\n======================================================================\nFAIL: test29 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 186, in test29\n    self.assertEqual(patched_source(input_29), original_source(input_29))\nAssertionError: Lists differ: [3] != [2]\n\nFirst differing element 0:\n3\n2\n\n- [3]\n+ [2]\n\n======================================================================\nFAIL: test39 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 246, in test39\n    self.assertEqual(patched_source(input_39), original_source(input_39))\nAssertionError: Lists differ: [2] != [1]\n\nFirst differing element 0:\n2\n1\n\n- [2]\n+ [1]\n\n======================================================================\nFAIL: test41 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 258, in test41\n    self.assertEqual(patched_source(input_41), original_source(input_41))\nAssertionError: Lists differ: [4] != [3]\n\nFirst differing element 0:\n4\n3\n\n- [4]\n+ [3]\n\n======================================================================\nFAIL: test54 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 336, in test54\n    self.assertEqual(patched_source(input_54), original_source(input_54))\nAssertionError: Lists differ: [3] != [2]\n\nFirst differing element 0:\n3\n2\n\n- [3]\n+ [2]\n\n======================================================================\nFAIL: test7 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 54, in test7\n    self.assertEqual(patched_source(input_7), original_source(input_7))\nAssertionError: Lists differ: [3] != [2]\n\nFirst differing element 0:\n3\n2\n\n- [3]\n+ [2]\n\n======================================================================\nFAIL: test88 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 540, in test88\n    self.assertEqual(patched_source(input_88), original_source(input_88))\nAssertionError: Lists differ: [5] != [4]\n\nFirst differing element 0:\n5\n4\n\n- [5]\n+ [4]\n\n----------------------------------------------------------------------\nRan 100 tests in 0.006s\n\nFAILED (failures=9)\n')