CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'FFFFFFFFFFFFFFFFF.FFFFFFF\n======================================================================\nFAIL: test0 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 12, in test0\n    self.assertEqual(patched_source(input_0), original_source(input_0))\nAssertionError: Lists differ: [5] != [0]\n\nFirst differing element 0:\n5\n0\n\n- [5]\n+ [0]\n\n======================================================================\nFAIL: test1 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 18, in test1\n    self.assertEqual(patched_source(input_1), original_source(input_1))\nAssertionError: Lists differ: [5] != [0]\n\nFirst differing element 0:\n5\n0\n\n- [5]\n+ [0]\n\n======================================================================\nFAIL: test10 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 72, in test10\n    self.assertEqual(patched_source(input_10), original_source(input_10))\nAssertionError: Lists differ: [4] != [0]\n\nFirst differing element 0:\n4\n0\n\n- [4]\n+ [0]\n\n======================================================================\nFAIL: test11 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 78, in test11\n    self.assertEqual(patched_source(input_11), original_source(input_11))\nAssertionError: Lists differ: [4] != [0]\n\nFirst differing element 0:\n4\n0\n\n- [4]\n+ [0]\n\n======================================================================\nFAIL: test12 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 84, in test12\n    self.assertEqual(patched_source(input_12), original_source(input_12))\nAssertionError: Lists differ: [2] != [0]\n\nFirst differing element 0:\n2\n0\n\n- [2]\n+ [0]\n\n======================================================================\nFAIL: test13 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 90, in test13\n    self.assertEqual(patched_source(input_13), original_source(input_13))\nAssertionError: Lists differ: [2] != [0]\n\nFirst differing element 0:\n2\n0\n\n- [2]\n+ [0]\n\n======================================================================\nFAIL: test14 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 96, in test14\n    self.assertEqual(patched_source(input_14), original_source(input_14))\nAssertionError: Lists differ: [10] != [0]\n\nFirst differing element 0:\n10\n0\n\n- [10]\n?  -\n\n+ [0]\n\n======================================================================\nFAIL: test15 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 102, in test15\n    self.assertEqual(patched_source(input_15), original_source(input_15))\nAssertionError: Lists differ: [2] != [0]\n\nFirst differing element 0:\n2\n0\n\n- [2]\n+ [0]\n\n======================================================================\nFAIL: test16 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 108, in test16\n    self.assertEqual(patched_source(input_16), original_source(input_16))\nAssertionError: Lists differ: [5] != [0]\n\nFirst differing element 0:\n5\n0\n\n- [5]\n+ [0]\n\n======================================================================\nFAIL: test17 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 114, in test17\n    self.assertEqual(patched_source(input_17), original_source(input_17))\nAssertionError: Lists differ: [3] != [0]\n\nFirst differing element 0:\n3\n0\n\n- [3]\n+ [0]\n\n======================================================================\nFAIL: test18 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 120, in test18\n    self.assertEqual(patched_source(input_18), original_source(input_18))\nAssertionError: Lists differ: [5] != [0]\n\nFirst differing element 0:\n5\n0\n\n- [5]\n+ [0]\n\n======================================================================\nFAIL: test19 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 126, in test19\n    self.assertEqual(patched_source(input_19), original_source(input_19))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test2 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 24, in test2\n    self.assertEqual(patched_source(input_2), original_source(input_2))\nAssertionError: Lists differ: [5] != [0]\n\nFirst differing element 0:\n5\n0\n\n- [5]\n+ [0]\n\n======================================================================\nFAIL: test20 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 132, in test20\n    self.assertEqual(patched_source(input_20), original_source(input_20))\nAssertionError: Lists differ: [5] != [0]\n\nFirst differing element 0:\n5\n0\n\n- [5]\n+ [0]\n\n======================================================================\nFAIL: test21 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 138, in test21\n    self.assertEqual(patched_source(input_21), original_source(input_21))\nAssertionError: Lists differ: [5] != [0]\n\nFirst differing element 0:\n5\n0\n\n- [5]\n+ [0]\n\n======================================================================\nFAIL: test22 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 144, in test22\n    self.assertEqual(patched_source(input_22), original_source(input_22))\nAssertionError: Lists differ: [10] != [0]\n\nFirst differing element 0:\n10\n0\n\n- [10]\n?  -\n\n+ [0]\n\n======================================================================\nFAIL: test23 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 150, in test23\n    self.assertEqual(patched_source(input_23), original_source(input_23))\nAssertionError: Lists differ: [5] != [0]\n\nFirst differing element 0:\n5\n0\n\n- [5]\n+ [0]\n\n======================================================================\nFAIL: test3 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 30, in test3\n    self.assertEqual(patched_source(input_3), original_source(input_3))\nAssertionError: Lists differ: [5] != [0]\n\nFirst differing element 0:\n5\n0\n\n- [5]\n+ [0]\n\n======================================================================\nFAIL: test4 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 36, in test4\n    self.assertEqual(patched_source(input_4), original_source(input_4))\nAssertionError: Lists differ: [5] != [0]\n\nFirst differing element 0:\n5\n0\n\n- [5]\n+ [0]\n\n======================================================================\nFAIL: test5 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 42, in test5\n    self.assertEqual(patched_source(input_5), original_source(input_5))\nAssertionError: Lists differ: [5] != [0]\n\nFirst differing element 0:\n5\n0\n\n- [5]\n+ [0]\n\n======================================================================\nFAIL: test6 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 48, in test6\n    self.assertEqual(patched_source(input_6), original_source(input_6))\nAssertionError: Lists differ: [5] != [0]\n\nFirst differing element 0:\n5\n0\n\n- [5]\n+ [0]\n\n======================================================================\nFAIL: test7 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 54, in test7\n    self.assertEqual(patched_source(input_7), original_source(input_7))\nAssertionError: Lists differ: [5] != [0]\n\nFirst differing element 0:\n5\n0\n\n- [5]\n+ [0]\n\n======================================================================\nFAIL: test8 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 60, in test8\n    self.assertEqual(patched_source(input_8), original_source(input_8))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test9 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 66, in test9\n    self.assertEqual(patched_source(input_9), original_source(input_9))\nAssertionError: Lists differ: [5] != [0]\n\nFirst differing element 0:\n5\n0\n\n- [5]\n+ [0]\n\n----------------------------------------------------------------------\nRan 25 tests in 0.005s\n\nFAILED (failures=24)\n')