============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.4.4, pluggy-1.4.0
rootdir: /home/khashayar/projs/det-gen
plugins: anyio-4.3.0
collected 3 items

c4b_bak/src_2649/2/test_transformed_src_2649.py .F.                      [100%]

=================================== FAILURES ===================================
_________________________________ test_case_1 __________________________________

    def test_case_1():
        bytes_0 = b"\x17\x02\xcc\xc4\x12j\xd4p\xf2\xc3?\xccd"
        var_0 = module_0.func(*bytes_0)
>       assert var_0 == 11
E       assert 22 == 11

c4b_bak/src_2649/2/test_transformed_src_2649.py:22: AssertionError
=========================== short test summary info ============================
FAILED c4b_bak/src_2649/2/test_transformed_src_2649.py::test_case_1 - assert ...
========================= 1 failed, 2 passed in 0.03s ==========================
