============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.4.4, pluggy-1.4.0
rootdir: /home/khashayar/projs/det-gen
plugins: anyio-4.3.0
collected 4 items

c4b_bak/src_1820/0/test_transformed_src_1820.py ..FF                     [100%]

=================================== FAILURES ===================================
_________________________________ test_case_2 __________________________________

    def test_case_2():
        int_0 = 60
        list_0 = [int_0, int_0]
        var_0 = module_0.func(*list_0)
>       assert var_0 == "YES"
E       AssertionError: assert 'NO' == 'YES'
E         - YES
E         + NO

c4b_bak/src_1820/0/test_transformed_src_1820.py:28: AssertionError
_________________________________ test_case_3 __________________________________

    def test_case_3():
        int_0 = 477
        list_0 = [int_0, int_0]
        var_0 = module_0.func(*list_0)
>       assert var_0 == "YES"
E       AssertionError: assert 'NO' == 'YES'
E         - YES
E         + NO

c4b_bak/src_1820/0/test_transformed_src_1820.py:37: AssertionError
=========================== short test summary info ============================
FAILED c4b_bak/src_1820/0/test_transformed_src_1820.py::test_case_2 - Asserti...
FAILED c4b_bak/src_1820/0/test_transformed_src_1820.py::test_case_3 - Asserti...
========================= 2 failed, 2 passed in 0.03s ==========================
