============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.4.4, pluggy-1.4.0
rootdir: /home/khashayar/projs/det-gen
plugins: anyio-4.3.0
collected 3 items

c4b_bak/src_1299/2/test_transformed_src_1299.py F.F                      [100%]

=================================== FAILURES ===================================
_________________________________ test_case_1 __________________________________

    def test_case_1():
        bytes_0 = b""
        bool_0 = False
        list_0 = [bool_0, bytes_0, bool_0, bool_0, bytes_0]
        var_0 = module_0.func(*list_0)
>       assert var_0 == 7
E       assert 0 == 7

c4b_bak/src_1299/2/test_transformed_src_1299.py:17: AssertionError
_________________________________ test_case_3 __________________________________

    def test_case_3():
        bytes_0 = b"1"
        bool_0 = False
        list_0 = [bool_0, bytes_0, bool_0, bool_0, bytes_0]
        var_0 = module_0.func(*list_0)
>       assert var_0 == 7
E       assert 0 == 7

c4b_bak/src_1299/2/test_transformed_src_1299.py:33: AssertionError
=========================== short test summary info ============================
FAILED c4b_bak/src_1299/2/test_transformed_src_1299.py::test_case_1 - assert ...
FAILED c4b_bak/src_1299/2/test_transformed_src_1299.py::test_case_3 - assert ...
========================= 2 failed, 1 passed in 0.04s ==========================
