CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'F.FF.....FFE\n======================================================================\nERROR: test9 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 66, in test9\n    self.assertEqual(patched_source(input_9), original_source(input_9))\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_acc_qb.py", line 24, in patched_func\n    d = binSearch(s, 1, int(n))\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_acc_qb.py", line 18, in binSearch\n    return binSearch(s, l, (((l + u) // 2) - 1))\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_acc_qb.py", line 18, in binSearch\n    return binSearch(s, l, (((l + u) // 2) - 1))\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_acc_qb.py", line 18, in binSearch\n    return binSearch(s, l, (((l + u) // 2) - 1))\n  [Previous line repeated 977 more times]\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_acc_qb.py", line 13, in binSearch\n    if ((((((l + u) // 2) + 1) - sumOfDigits((((l + u) // 2) + 1))) >= s) and ((((l + u) // 2) - sumOfDigits(((l + u) // 2))) < s)):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_acc_qb.py", line 7, in sumOfDigits\n    s = str(s)\nRecursionError: maximum recursion depth exceeded while getting the str of an object\n\n======================================================================\nFAIL: test0 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 12, in test0\n    self.assertEqual(patched_source(input_0), original_source(input_0))\nAssertionError: Lists differ: [91] != [50]\n\nFirst differing element 0:\n91\n50\n\n- [91]\n+ [50]\n\n======================================================================\nFAIL: test10 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 72, in test10\n    self.assertEqual(patched_source(input_10), original_source(input_10))\nAssertionError: Lists differ: [9999991] != [5000000]\n\nFirst differing element 0:\n9999991\n5000000\n\n- [9999991]\n+ [5000000]\n\n======================================================================\nFAIL: test11 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 78, in test11\n    self.assertEqual(patched_source(input_11), original_source(input_11))\nAssertionError: Lists differ: [91] != [50]\n\nFirst differing element 0:\n91\n50\n\n- [91]\n+ [50]\n\n======================================================================\nFAIL: test7 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 54, in test7\n    self.assertEqual(patched_source(input_7), original_source(input_7))\nAssertionError: Lists differ: [6] != [3]\n\nFirst differing element 0:\n6\n3\n\n- [6]\n+ [3]\n\n======================================================================\nFAIL: test8 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 60, in test8\n    self.assertEqual(patched_source(input_8), original_source(input_8))\nAssertionError: Lists differ: [16] != [8]\n\nFirst differing element 0:\n16\n8\n\n- [16]\n+ [8]\n\n----------------------------------------------------------------------\nRan 12 tests in 0.011s\n\nFAILED (failures=5, errors=1)\n')